import {
  Git,
  JavaScript,
  Jest,
  Kotlin,
  Laravel,
  Markdown,
  MySQL,
  NextJS,
  NuxtJS,
  PHP,
  PostgreSQL,
  Prisma,
  RabbitMQ,
  ReactJS,
  Redis,
  Ruby,
  RubyOnRails,
  Spring,
  TailwindCSS,
  TypeScript,
  VueJS,
} from '@/components/shared/icons';
import { cn } from '@/lib/utils';
import type { Stack } from '@/types/stack';

export const STACKS: Stack = {
  TypeScript: <TypeScript className={cn('size-4 fill-[#3178C6]')} />,
  JavaScript: <JavaScript className={cn('size-4 fill-[#F7DF1E]')} />,
  PHP: <PHP className={cn('size-4 fill-[#777BB4]')} />,
  Kotlin: <Kotlin className={cn('size-4 fill-[#7F52FF]')} />,
  Ruby: <Ruby className={cn('size-4 fill-[#CC342D]')} />,
  'Next.js': <NextJS className={cn('size-4 fill-black', 'dark:fill-white')} />,
  'React.js': <ReactJS className={cn('size-4 fill-[#61DAFB]')} />,
  'Nuxt.js': <NuxtJS className={cn('size-4 fill-[#00DC82]')} />,
  'Vue.js': <VueJS className={cn('size-4 fill-[#4FC08D]')} />,
  Laravel: <Laravel className={cn('size-4 fill-[#FF2D20]')} />,
  Spring: <Spring className={cn('size-4 fill-[#6DB33F]')} />,
  'Ruby on Rails': <RubyOnRails className={cn('size-4 fill-[#D30001]')} />,
  'Tailwind CSS': <TailwindCSS className={cn('size-4 fill-[#06B6D4]')} />,
  Markdown: <Markdown className={cn('size-4 fill-black', 'dark:fill-white')} />,
  MySQL: <MySQL className={cn('size-4 fill-[#4479A1]')} />,
  PostgreSQL: <PostgreSQL className={cn('size-4 fill-[#4169E1]')} />,
  Redis: <Redis className={cn('size-4 fill-[#FF4438]')} />,
  Prisma: (
    <Prisma className={cn('size-4 fill-[##2D3748]', 'dark:fill-white')} />
  ),
  RabbitMQ: <RabbitMQ className={cn('size-4 fill-[#FF6600]')} />,
  Jest: <Jest className={cn('size-4 fill-[#C21325]')} />,
  Git: <Git className={cn('size-4 fill-[#F05032]')} />,
};
