DROP TABLE IF EXISTS `views`;

CREATE TABLE IF NOT EXISTS `counters` (
  `slug` VARCHAR(128) NOT NULL,
  `views` BIGINT NOT NULL DEFAULT 1,
  `loves` BIGINT NOT NULL DEFAULT 1,
  `likes` BIGINT NOT NULL DEFAULT 1,
  `claps` BIGINT NOT NULL DEFAULT 1,
  `bookmarks` BIGINT NOT NULL DEFAULT 1,

  PRIMARY KEY (`slug`)
)
