ALTER TABLE `counters`
  MODIFY COLUMN `slug` VARCHAR(128) NOT NULL,
  MODIFY COLUMN `views` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `loves` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `likes` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `stars` BIGINT NOT NULL DEFAULT 0;
